# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e7a0efa2d21a670eb6ba184fabc8e73020d1e97099b04ed0e1eab8561f4d17b14e7a3b6de157b8e652d105ac74333ab111468b8de4fa9391e3fa0dfa16c4b89

test:
  secret_key_base: 24db8cb35f4ee31d738a38c5a46139d64f1e51aa5e09116be7e4c6a77d6ec1064d9e55f25b826fc562e0c1bc77d2d4b26419e3b4ca5a95e4eba7a587dd4afbda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
